// Mocks generated by Mockito 5.2.0 from annotations
// in qelem/test/repo_tests/answer/answer_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qelem/data/local/local_database/qelem_local_storage.dart'
    as _i4;
import 'package:qelem/domain/answer/answer.dart' as _i8;
import 'package:qelem/domain/answer/answer_form.dart' as _i9;
import 'package:qelem/domain/common/vote.dart' as _i10;
import 'package:qelem/infrastructure/answer/answer_api.dart' as _i2;
import 'package:qelem/infrastructure/answer/answer_repoistory.dart' as _i6;
import 'package:qelem/infrastructure/question/question_api.dart' as _i3;
import 'package:qelem/util/either.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAnswerApi_0 extends _i1.Fake implements _i2.AnswerApi {}

class _FakeQuestionApi_1 extends _i1.Fake implements _i3.QuestionApi {}

class _FakeDatabaseHelper_2 extends _i1.Fake implements _i4.DatabaseHelper {}

class _FakeEither_3<T> extends _i1.Fake implements _i5.Either<T> {}

/// A class which mocks [AnswerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnswerRepository extends _i1.Mock implements _i6.AnswerRepository {
  MockAnswerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnswerApi get answerApi =>
      (super.noSuchMethod(Invocation.getter(#answerApi),
          returnValue: _FakeAnswerApi_0()) as _i2.AnswerApi);
  @override
  _i3.QuestionApi get questionApi =>
      (super.noSuchMethod(Invocation.getter(#questionApi),
          returnValue: _FakeQuestionApi_1()) as _i3.QuestionApi);
  @override
  _i4.DatabaseHelper get databaseHelper =>
      (super.noSuchMethod(Invocation.getter(#databaseHelper),
          returnValue: _FakeDatabaseHelper_2()) as _i4.DatabaseHelper);
  @override
  _i7.Future<_i5.Either<List<_i8.Answer>>> getAnswerForQuestion(
          int? questionId) =>
      (super.noSuchMethod(
              Invocation.method(#getAnswerForQuestion, [questionId]),
              returnValue: Future<_i5.Either<List<_i8.Answer>>>.value(
                  _FakeEither_3<List<_i8.Answer>>()))
          as _i7.Future<_i5.Either<List<_i8.Answer>>>);
  @override
  _i7.Future<_i5.Either<_i8.Answer>> getAnswerById(int? answerId) =>
      (super.noSuchMethod(Invocation.method(#getAnswerById, [answerId]),
              returnValue: Future<_i5.Either<_i8.Answer>>.value(
                  _FakeEither_3<_i8.Answer>()))
          as _i7.Future<_i5.Either<_i8.Answer>>);
  @override
  _i7.Future<_i5.Either<_i8.Answer>> createAnswer(
          {_i9.AnswerForm? answerForm}) =>
      (super.noSuchMethod(
              Invocation.method(#createAnswer, [], {#answerForm: answerForm}),
              returnValue: Future<_i5.Either<_i8.Answer>>.value(
                  _FakeEither_3<_i8.Answer>()))
          as _i7.Future<_i5.Either<_i8.Answer>>);
  @override
  _i7.Future<_i5.Either<void>> deleteAnswer(int? answerId) =>
      (super.noSuchMethod(Invocation.method(#deleteAnswer, [answerId]),
              returnValue:
                  Future<_i5.Either<void>>.value(_FakeEither_3<void>()))
          as _i7.Future<_i5.Either<void>>);
  @override
  _i7.Future<_i5.Either<_i8.Answer>> updateAnswer(_i8.Answer? answer) =>
      (super.noSuchMethod(Invocation.method(#updateAnswer, [answer]),
              returnValue: Future<_i5.Either<_i8.Answer>>.value(
                  _FakeEither_3<_i8.Answer>()))
          as _i7.Future<_i5.Either<_i8.Answer>>);
  @override
  _i7.Future<_i5.Either<_i8.Answer>> voteAnswer(
          int? answerId, _i10.Vote? vote) =>
      (super.noSuchMethod(Invocation.method(#voteAnswer, [answerId, vote]),
              returnValue: Future<_i5.Either<_i8.Answer>>.value(
                  _FakeEither_3<_i8.Answer>()))
          as _i7.Future<_i5.Either<_i8.Answer>>);
  @override
  _i7.Future<_i5.Either<List<_i8.Answer>>> getAnswersByQuestionId(
          int? questionId) =>
      (super.noSuchMethod(
              Invocation.method(#getAnswersByQuestionId, [questionId]),
              returnValue: Future<_i5.Either<List<_i8.Answer>>>.value(
                  _FakeEither_3<List<_i8.Answer>>()))
          as _i7.Future<_i5.Either<List<_i8.Answer>>>);
  @override
  _i7.Future<_i5.Either<List<_i8.Answer>>> getAllAnswers() =>
      (super.noSuchMethod(Invocation.method(#getAllAnswers, []),
              returnValue: Future<_i5.Either<List<_i8.Answer>>>.value(
                  _FakeEither_3<List<_i8.Answer>>()))
          as _i7.Future<_i5.Either<List<_i8.Answer>>>);
}
