// Mocks generated by Mockito 5.2.0 from annotations
// in qelem/test/answer_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qelem/domain/answer/answer.dart' as _i5;
import 'package:qelem/domain/answer/answer_form.dart' as _i6;
import 'package:qelem/domain/auth/user.dart' as _i4;
import 'package:qelem/domain/common/vote.dart' as _i9;
import 'package:qelem/infrastructure/answer/answer_api.dart' as _i2;
import 'package:qelem/infrastructure/answer/answer_repoistory.dart' as _i7;
import 'package:qelem/util/either.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAnswerApi_0 extends _i1.Fake implements _i2.AnswerApi {}

class _FakeEither_1<T> extends _i1.Fake implements _i3.Either<T> {}

class _FakeUser_2 extends _i1.Fake implements _i4.User {}

class _FakeDateTime_3 extends _i1.Fake implements DateTime {}

class _Fake$AnswerCopyWith_4<$Res> extends _i1.Fake
    implements _i5.$AnswerCopyWith<$Res> {}

class _Fake$AnswerFormCopyWith_5<$Res> extends _i1.Fake
    implements _i6.$AnswerFormCopyWith<$Res> {}

/// A class which mocks [AnswerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnswerRepository extends _i1.Mock implements _i7.AnswerRepository {
  MockAnswerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnswerApi get answerApi =>
      (super.noSuchMethod(Invocation.getter(#answerApi),
          returnValue: _FakeAnswerApi_0()) as _i2.AnswerApi);
  @override
  _i8.Future<_i3.Either<List<_i5.Answer>>> getAllAnswers() =>
      (super.noSuchMethod(Invocation.method(#getAllAnswers, []),
              returnValue: Future<_i3.Either<List<_i5.Answer>>>.value(
                  _FakeEither_1<List<_i5.Answer>>()))
          as _i8.Future<_i3.Either<List<_i5.Answer>>>);
  @override
  _i8.Future<_i3.Either<_i5.Answer>> getAnswerById(int? answerId) =>
      (super.noSuchMethod(Invocation.method(#getAnswerById, [answerId]),
              returnValue: Future<_i3.Either<_i5.Answer>>.value(
                  _FakeEither_1<_i5.Answer>()))
          as _i8.Future<_i3.Either<_i5.Answer>>);
  @override
  _i8.Future<_i3.Either<_i5.Answer>> createAnswer(
          {_i6.AnswerForm? answerForm}) =>
      (super.noSuchMethod(
              Invocation.method(#createAnswer, [], {#answerForm: answerForm}),
              returnValue: Future<_i3.Either<_i5.Answer>>.value(
                  _FakeEither_1<_i5.Answer>()))
          as _i8.Future<_i3.Either<_i5.Answer>>);
  @override
  _i8.Future<_i3.Either<void>> deleteAnswer(int? answerId) =>
      (super.noSuchMethod(Invocation.method(#deleteAnswer, [answerId]),
              returnValue:
                  Future<_i3.Either<void>>.value(_FakeEither_1<void>()))
          as _i8.Future<_i3.Either<void>>);
  @override
  _i8.Future<_i3.Either<_i5.Answer>> updateAnswer(_i5.Answer? answer) =>
      (super.noSuchMethod(Invocation.method(#updateAnswer, [answer]),
              returnValue: Future<_i3.Either<_i5.Answer>>.value(
                  _FakeEither_1<_i5.Answer>()))
          as _i8.Future<_i3.Either<_i5.Answer>>);
  @override
  _i8.Future<_i3.Either<_i5.Answer>> voteAnswer(
          int? answerId, _i9.Vote? vote) =>
      (super.noSuchMethod(Invocation.method(#voteAnswer, [answerId, vote]),
              returnValue: Future<_i3.Either<_i5.Answer>>.value(
                  _FakeEither_1<_i5.Answer>()))
          as _i8.Future<_i3.Either<_i5.Answer>>);
  @override
  _i8.Future<_i3.Either<List<_i5.Answer>>> getAnswersByQuestionId(
          int? questionId) =>
      (super.noSuchMethod(
              Invocation.method(#getAnswersByQuestionId, [questionId]),
              returnValue: Future<_i3.Either<List<_i5.Answer>>>.value(
                  _FakeEither_1<List<_i5.Answer>>()))
          as _i8.Future<_i3.Either<List<_i5.Answer>>>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i4.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get userName =>
      (super.noSuchMethod(Invocation.getter(#userName), returnValue: '')
          as String);
  @override
  String get firstName =>
      (super.noSuchMethod(Invocation.getter(#firstName), returnValue: '')
          as String);
  @override
  String get lastName =>
      (super.noSuchMethod(Invocation.getter(#lastName), returnValue: '')
          as String);
  @override
  String get profilePicture =>
      (super.noSuchMethod(Invocation.getter(#profilePicture), returnValue: '')
          as String);
}

/// A class which mocks [Answer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnswer extends _i1.Mock implements _i5.Answer {
  MockAnswer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get content =>
      (super.noSuchMethod(Invocation.getter(#content), returnValue: '')
          as String);
  @override
  int get questionId =>
      (super.noSuchMethod(Invocation.getter(#questionId), returnValue: 0)
          as int);
  @override
  _i4.User get author => (super.noSuchMethod(Invocation.getter(#author),
      returnValue: _FakeUser_2()) as _i4.User);
  @override
  int get upVotes =>
      (super.noSuchMethod(Invocation.getter(#upVotes), returnValue: 0) as int);
  @override
  int get downVotes =>
      (super.noSuchMethod(Invocation.getter(#downVotes), returnValue: 0)
          as int);
  @override
  _i9.Vote get userVote => (super.noSuchMethod(Invocation.getter(#userVote),
      returnValue: _i9.Vote.upVote) as _i9.Vote);
  @override
  DateTime get createdAt => (super.noSuchMethod(Invocation.getter(#createdAt),
      returnValue: _FakeDateTime_3()) as DateTime);
  @override
  DateTime get updatedAt => (super.noSuchMethod(Invocation.getter(#updatedAt),
      returnValue: _FakeDateTime_3()) as DateTime);
  @override
  _i5.$AnswerCopyWith<_i5.Answer> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$AnswerCopyWith_4<_i5.Answer>())
          as _i5.$AnswerCopyWith<_i5.Answer>);
}

/// A class which mocks [AnswerForm].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnswerForm extends _i1.Mock implements _i6.AnswerForm {
  MockAnswerForm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get questionId =>
      (super.noSuchMethod(Invocation.getter(#questionId), returnValue: 0)
          as int);
  @override
  String get content =>
      (super.noSuchMethod(Invocation.getter(#content), returnValue: '')
          as String);
  @override
  _i6.$AnswerFormCopyWith<_i6.AnswerForm> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$AnswerFormCopyWith_5<_i6.AnswerForm>())
          as _i6.$AnswerFormCopyWith<_i6.AnswerForm>);
}
