// Mocks generated by Mockito 5.2.0 from annotations
// in qelem/test/repo_tests/profile_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qelem/domain/profile/edit_profile_form.dart' as _i7;
import 'package:qelem/domain/profile/profile.dart' as _i6;
import 'package:qelem/infrastructure/profile/profile_api.dart' as _i2;
import 'package:qelem/infrastructure/profile/profile_repository.dart' as _i4;
import 'package:qelem/util/either.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeProfileApi_0 extends _i1.Fake implements _i2.ProfileApi {}

class _FakeEither_1<T> extends _i1.Fake implements _i3.Either<T> {}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i4.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileApi get profileApi =>
      (super.noSuchMethod(Invocation.getter(#profileApi),
          returnValue: _FakeProfileApi_0()) as _i2.ProfileApi);
  @override
  _i5.Future<_i3.Either<_i6.Profile>> updateProfile(
          {_i7.EditProfileForm? profileForm}) =>
      (super.noSuchMethod(
          Invocation.method(#updateProfile, [], {#profileForm: profileForm}),
          returnValue: Future<_i3.Either<_i6.Profile>>.value(
              _FakeEither_1<_i6.Profile>())) as _i5
          .Future<_i3.Either<_i6.Profile>>);
  @override
  _i5.Future<_i3.Either<_i6.Profile>> getProfile() =>
      (super.noSuchMethod(Invocation.method(#getProfile, []),
              returnValue: Future<_i3.Either<_i6.Profile>>.value(
                  _FakeEither_1<_i6.Profile>()))
          as _i5.Future<_i3.Either<_i6.Profile>>);
  @override
  _i5.Future<_i3.Either<void>> deleteAccount() => (super.noSuchMethod(
          Invocation.method(#deleteAccount, []),
          returnValue: Future<_i3.Either<void>>.value(_FakeEither_1<void>()))
      as _i5.Future<_i3.Either<void>>);
}
