// Mocks generated by Mockito 5.2.0 from annotations
// in qelem/test/repo_tests/profile/profile_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qelem/domain/profile/edit_profile_form.dart' as _i6;
import 'package:qelem/domain/profile/profile.dart' as _i5;
import 'package:qelem/domain/profile/profile_repository_interface.dart' as _i3;
import 'package:qelem/util/either.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<T> extends _i1.Fake implements _i2.Either<T> {}

/// A class which mocks [ProfileRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepositoryInterface extends _i1.Mock
    implements _i3.ProfileRepositoryInterface {
  MockProfileRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Profile>> updateProfile(
          {_i6.EditProfileForm? profileForm}) =>
      (super.noSuchMethod(
          Invocation.method(#updateProfile, [], {#profileForm: profileForm}),
          returnValue: Future<_i2.Either<_i5.Profile>>.value(
              _FakeEither_0<_i5.Profile>())) as _i4
          .Future<_i2.Either<_i5.Profile>>);
  @override
  _i4.Future<_i2.Either<_i5.Profile>> getProfile() =>
      (super.noSuchMethod(Invocation.method(#getProfile, []),
              returnValue: Future<_i2.Either<_i5.Profile>>.value(
                  _FakeEither_0<_i5.Profile>()))
          as _i4.Future<_i2.Either<_i5.Profile>>);
  @override
  _i4.Future<_i2.Either<void>> deleteAccount() => (super.noSuchMethod(
          Invocation.method(#deleteAccount, []),
          returnValue: Future<_i2.Either<void>>.value(_FakeEither_0<void>()))
      as _i4.Future<_i2.Either<void>>);
}
