name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '2.10.x'
            channel: 'stable'
            cache: true
            cache-key: flutter
            cache-path: ${{ runner.tool_cache }}/flutter
            architecture: x64
        - run: pwd
        - run: cd qelem
        - run: pwd
        - run: flutter pub get
        - run: flutter test
        - run: flutter build apk
        - run: flutter build appbundle
  
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.x'
        channel: 'stable'
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter
        architecture: x64
    - run: pwd
    - run: cd qelem
    - run: pwd
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
    
